language: node_js

os:
  - linux
  - osx

node_js: "8.2.1"


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update && sudo apt-get install -q libxss-dev; fi

before_script:
  - composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
  - composer show -i 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3; fi

script:
  - npm install -g istanbul
  - istanbul cover ./node_modules/mocha/bin/_mocha
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn dist; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn dist-all; f

notifications:
  email:
    on_success: never
    on_failure: change

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  on_success: never
  on_failure: never

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true

