language: node_js

os:
  - linux
  - osx

node_js: '8.16.0'

services:
  - xvfb

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update && sudo apt-get install -q libxss-dev; fi

script:
  - npm install -g nyc
  - npx nyc mocha
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn dist; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn dist-all; fi

notifications:
  email:
    on_success: never
    on_failure: change

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key: 
    secure: '$GITHUB_API_KEY'
  file:
    - 'dist/vagrant-manager.dmg'
    - 'dist/vagrant-manager.appx'
    - 'dist/vagrant-manager.exe'
    - 'dist/vagrant-manager-web-setup.exe'
    - 'dist/vagrant-manager-i386.AppImage'
    - 'dist/vagrant-manager-x86_64.AppImage'
    - 'dist/vagrant-manager-i686.rpm'
    - 'dist/vagrant-manager-x86_64.rpm'
    - 'dist/vagrant-manager-amd64.deb'
    - 'dist/vagrant-manager-i386.deb' 
  skip_cleanup: true
  on:
    tags: true
