image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  
init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn install
  - yarn upgrade
  - npm install -g istanbul

build_script:
  - yarn dist
  
test_script:
  - node --version
  - npm --version
  - istanbul cover .\node_modules\mocha\bin\_mocha
  - yarn dist

after_test:
- bash <(curl -s https://codecov.io/bash)
