image: Visual Studio 2017

platform:
  - x64

# cache:
#  - node_modules
#  - '%USERPROFILE%\.electron'
  
init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - yarn install
  - yarn upgrade
  - npm install -g nyc

build_script:
  - yarn dist
  
test_script:
  - node --version
  - npm --version
  - npx nyc mocha
  - yarn dist

after_test:
- bash <(curl -s https://codecov.io/bash)
