image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  
environment:
    nodejs_version: "8.2.1" 

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $nodejs_version x64
  - npm install
  - npm install npm -g 
  - npm install -g istanbul

build_script:
  - yarn dist
  
test_script:
  - node --version
  - npm --version
  - istanbul cover .\node_modules\mocha\bin\_mocha
  - yarn dist

after_test:
- bash <(curl -s https://codecov.io/bash)
